export default {
    products: [
      {
        _id: '111111111111111111111111',
        name:'Full Zip Running Shirts',
        category: 'Shirts',
        image: '/images/product-1.jpg',
        price: 60,
        brand: 'Nike',
        rating: 3.5,
        numReviews: 14,
        countInStock: 10,
      },
      {
        _id: '222222222222222222222222',
        name:'Jacket Shirts',
        category: 'Shirts',
        image: '/images/product-2.jpg',
        price: 70,
        brand: 'Nike',
        rating: 5.0,
        numReviews: 16,
        countInStock: 6,
      },
      {
        _id: '3',
        name:'Shoe',
        category: 'Shoe',
        image: '/images/product-3.jpg',
        price: 60,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 40,
        countInStock: 16,
      },
      {
        _id: '4',
        name:'Full Zip Running Shirts',
        category: 'Shirts',
        image: '/images/product-4.jpg',
        price: 40,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 40,
      },
      {
        _id: '5',
        name:'Touser',
        category: 'Shoe',
        image: '/images/product-5.jpg',
        price: 190,
        brand: 'Nike',
        rating: 2.5,
        numReviews: 6,
        countInStock: 20,
      },
      {
        _id: '6',
        name:'Big Touser',
        category: 'Shoe',
        image: '/images/product-6.jpg',
        price: 160,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 90,
        countInStock: 16,
      },
    ],
};
